version: '2'

services:
  web:
    build: ./web
    ports:
      - "80:5000"
    depends_on:
      - redis
    expose:
      - "5000"
    environment:
      TEST_ENV: hello
    labels:
      io.resin.features.dbus: "true"
      io.resin.features.kernel_modules: "true"
      io.resin.features.firmware: "true"
      io.resin.features.supervisor_api: "true"
  redis:
    image: arm32v7/redis
    volumes:
      - data-volume:/containers-shared

volumes:
  data-volume:
